linters:
  enable-all: true
  disable:
    - nosnakecase #deprecated
    - structcheck #deprecated
    - interfacer #deprecated
    - ifshort #deprecated
    - scopelint #deprecated
    - varcheck #deprecated
    - golint #deprecated
    - maligned #deprecated
    - deadcode #deprecated
    - exhaustivestruct #deprecated
    - exhaustruct
    - rowserrcheck
    - sqlclosecheck
    - wastedassign
    - gomnd
    - gochecknoglobals
    - forbidigo
    - lll
    - paralleltest
    - wrapcheck
    - goerr113
    - varnamelen

linters-settings:
  govet:
    enable-all: true